switch:
  - platform: solar_lighting
    name: Downstairs Solar Lighting
    
    intercept_turn_on: True
    update_delta: 2 # or False
    control_delta: 5 # or False

    brightness_adjust: True
    brightness_min: 20
    brightness_max: 100
    brightness_k: 1.0
    brightness_x: 0.0

    temperature_adjust: True
    temperature_min: 2500
    temperature_max: 6000
    temperature_k: 0.5
    temperature_x: 0.5

    transition: 5
    update_interval: 60

    sleep_brightness: 5
    sleep_temperature: 2000

    lights:
      - light.kitchen_spots
      - entity_id: light.all_kitchent
        update_delta: False
      
